name: kaddep_data_capture
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+3

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.2.1
  flutter_bloc: ^8.1.3
  path_provider: ^2.0.11
  hive: ^2.2.3
  loading_indicator: ^3.1.0
  modal_bottom_sheet: ^2.0.0
  flutter_slidable: ^2.0.0
  cached_network_image: ^3.2.0
  colorize_text_avatar: ^1.0.1
  number_display: ^3.0.0
  numeral: ^2.0.1
  expandable_text: ^2.3.0
  introduction_screen: ^3.1.12
  flutter_countdown_timer: ^4.1.0
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.0.2
  filesize: ^2.0.1
  permission_handler: ^6.0.1
  record: ^4.4.4
  just_audio: ^0.9.31
  geolocator: ^9.0.2
  flutter_typeahead: ^4.1.1
  banner_carousel: ^1.2.1
  dio: ^4.0.6
  infinite_carousel: ^1.0.2
  async: ^2.10.0
  dropdown_textfield: ^1.0.8
  flutter_map: ^6.1.0
  map_launcher: ^2.5.0+1
  timeline_tile: ^2.0.0
  date_time_format: ^2.0.1
  flutter_svg_provider: ^1.0.6
  dotted_border: ^2.1.0
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  sidebarx: ^0.16.3
  easy_stepper: ^0.8.3
  textfield_datepicker: ^0.2.0
  intl: ^0.18.0
  sqflite: ^2.3.1
  syncfusion_flutter_charts: ^24.2.3
  syncfusion_flutter_pdfviewer: ^24.2.3
  share_plus: ^7.2.2
  video_thumbnail: ^0.5.3
  video_player: ^2.8.2
  flutter_image_compress: ^2.1.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.3.1
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-small.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/files/
    - assets/videos/
    - assets/