enum OGDataField{
  rid,
  id,
  firstName,
  lastName,
  dob,
  gender,
  phone,
  phoneNumber,
  email,
  bvn,
  nin,
  idDocument,
  ownerPassportPhotoUrl,
  address,
  homeAddress,
  civilServant,
  isCivilServant,
  businessName,
  businessAddress,
  businessLGA,
  businessLGACode,
  businessWard,
  businessRegCat,
  businessRegIssuer,
  businessRegNo,
  businessRegNum,
  ownerAtBusinessPhotoUrl,
  yearsInOperation,
  numStaff,
  businessOpsExpenseCat,
  itemsPurchased,
  itemPurchased1,
  itemPurchased2,
  itemPurchased3,
  salaryRenum,
  costOfItems,
  accountName,
  bank,
  accountNumber,
  tax,
  tin,
  tinIssuer,
  longitude,
  latitude,
  dataType,
  syncStatus,
  dataComplete,
  serverVerified,
  syncErrorMessage,

  idDocType,
  idDocPhotoUrl,

  taxId,
  issuer,
  taxRegPhotoUrl,

  catType,
  certPhotoUrl,
  cacProofDocPhotoUrl,

  itemsList,
  receiptPhotoUrl,

  groupPhotoUrl,
  renumerationPhotoUrl,
  comment,

  createdAt,
  updatedAt,
}

List<OGDataField> oGFieldsForNewRecords = [
  OGDataField.id,
  OGDataField.firstName,
  OGDataField.lastName,
  OGDataField.dob,
  OGDataField.gender,
  OGDataField.phone,
  OGDataField.bvn,
  OGDataField.nin,

  OGDataField.idDocType,
  OGDataField.idDocPhotoUrl,

  OGDataField.email,
  OGDataField.ownerPassportPhotoUrl,
  OGDataField.homeAddress,
  OGDataField.civilServant,
  OGDataField.businessName,
  OGDataField.businessAddress,
  OGDataField.businessLGA,
  OGDataField.businessLGACode,
  OGDataField.businessWard,

  OGDataField.catType,
  OGDataField.certPhotoUrl,
  OGDataField.cacProofDocPhotoUrl,

  OGDataField.businessRegIssuer, //should be part of above schema
  OGDataField.businessRegNum,
  OGDataField.ownerAtBusinessPhotoUrl,
  OGDataField.latitude,
  OGDataField.longitude,
  OGDataField.yearsInOperation,
  OGDataField.numStaff,
  OGDataField.businessOpsExpenseCat,

  OGDataField.itemsPurchased,// parent, but array of:
  // OGDataField.itemsList,
  // OGDataField.receiptPhotoUrl,

  // OGDataField.salaryRenum,//parent
  OGDataField.groupPhotoUrl,
  OGDataField.renumerationPhotoUrl,
  OGDataField.comment,

  OGDataField.costOfItems,
  OGDataField.bank,
  OGDataField.accountNumber,
  OGDataField.accountName,

  // OGDataField.tax,//parent
  OGDataField.taxId,
  OGDataField.issuer,
  OGDataField.taxRegPhotoUrl,

  OGDataField.createdAt,
  OGDataField.updatedAt,

];

List<OGDataField> oGFieldsFromOldRecords = [
  OGDataField.firstName,
  OGDataField.lastName,
  OGDataField.dob,
  OGDataField.gender,
  OGDataField.phone,
  OGDataField.email,
  OGDataField.bvn,
  OGDataField.homeAddress,
  OGDataField.civilServant,
  OGDataField.businessName,
  OGDataField.businessAddress,
  OGDataField.businessLGA,
  OGDataField.businessRegCat,
  OGDataField.businessRegIssuer,
  OGDataField.businessRegNo,
  OGDataField.yearsInOperation,
  OGDataField.numStaff,
  OGDataField.businessOpsExpenseCat,
  OGDataField.itemPurchased1,
  OGDataField.itemPurchased2,
  OGDataField.itemPurchased3,
  OGDataField.costOfItems,
  OGDataField.accountName,
  OGDataField.bank,
  OGDataField.accountNumber,
  OGDataField.tin,
  OGDataField.tinIssuer,
];

List<List<OGDataField>> oGDatabaseFieldsPages = [
  [
    OGDataField.id,
    OGDataField.firstName,
    OGDataField.lastName,
    OGDataField.dob,
    OGDataField.gender,
    OGDataField.phone,
    OGDataField.bvn,
    OGDataField.nin,
    OGDataField.email,
    OGDataField.homeAddress,
    OGDataField.civilServant,
    OGDataField.businessName,
    OGDataField.businessAddress,
    OGDataField.businessLGA,
    OGDataField.businessLGACode,
    OGDataField.businessWard,
    OGDataField.catType,
    OGDataField.idDocType,
    OGDataField.businessRegIssuer,
    OGDataField.businessRegNum,
    OGDataField.latitude,
    OGDataField.longitude,
    OGDataField.yearsInOperation,
    OGDataField.numStaff,
    OGDataField.businessOpsExpenseCat,
    OGDataField.comment,
    OGDataField.costOfItems,
    OGDataField.bank,
    OGDataField.accountNumber,
    OGDataField.accountName,
    OGDataField.taxId,
    OGDataField.issuer,
    OGDataField.createdAt,
    OGDataField.updatedAt,
  ],
  [
    OGDataField.idDocPhotoUrl,
  ],
  [
    OGDataField.ownerPassportPhotoUrl,
  ],
  [
    OGDataField.certPhotoUrl,
    OGDataField.cacProofDocPhotoUrl,
  ],
  [
    OGDataField.ownerAtBusinessPhotoUrl,
  ],
  [
    OGDataField.itemsPurchased,
  ],
  [
    OGDataField.groupPhotoUrl,
  ],
  [
    OGDataField.renumerationPhotoUrl,
  ],
  [
    OGDataField.taxRegPhotoUrl,
  ]
];