INSERT INTO trades(trade,category) VALUES ('Artisans/Repairers','Nano');
INSERT INTO trades(trade,category) VALUES ('Barbers','Nano');
INSERT INTO trades(trade,category) VALUES ('Salons','Nano');
INSERT INTO trades(trade,category) VALUES ('Hair Braiders','Nano');
INSERT INTO trades(trade,category) VALUES ('Shoemakers/Leather','Nano');
INSERT INTO trades(trade,category) VALUES ('Graphic Designers','Nano');
INSERT INTO trades(trade,category) VALUES ('Draftsman','Nano');
INSERT INTO trades(trade,category) VALUES ('Photographers','Nano');
INSERT INTO trades(trade,category) VALUES ('Videographers','Nano');
INSERT INTO trades(trade,category) VALUES ('Arts, Crafts and Pottery','Nano');
INSERT INTO trades(trade,category) VALUES ('Firewood Sellers','Nano');
INSERT INTO trades(trade,category) VALUES ('Bricklayers','Nano');
INSERT INTO trades(trade,category) VALUES ('Plumbers','Nano');
INSERT INTO trades(trade,category) VALUES ('Electrician','Nano');
INSERT INTO trades(trade,category) VALUES ('Carpenter','Nano');
INSERT INTO trades(trade,category) VALUES ('Building Labourers','Nano');
INSERT INTO trades(trade,category) VALUES ('Installers','Nano');
INSERT INTO trades(trade,category) VALUES ('POP Fitters','Nano');
INSERT INTO trades(trade,category) VALUES ('Motor Mechanics','Nano');
INSERT INTO trades(trade,category) VALUES ('Motor Electricians','Nano');
INSERT INTO trades(trade,category) VALUES ('Motorcycle Repairers','Nano');
INSERT INTO trades(trade,category) VALUES ('Vulcanizers','Nano');
INSERT INTO trades(trade,category) VALUES ('Cooking Gas Sellers','Nano');
INSERT INTO trades(trade,category) VALUES ('GMS Repairers','Nano');
INSERT INTO trades(trade,category) VALUES ('POS Agents','Nano');
INSERT INTO trades(trade,category) VALUES ('Welders','Nano');
INSERT INTO trades(trade,category) VALUES ('Panel Beaters','Nano');
INSERT INTO trades(trade,category) VALUES ('Laundry','Nano');
INSERT INTO trades(trade,category) VALUES ('Tailors','Nano');
INSERT INTO trades(trade,category) VALUES ('Generator Repairers','Nano');
INSERT INTO trades(trade,category) VALUES ('Food Sellers','Nano');
INSERT INTO trades(trade,category) VALUES ('Fruit Sellers','Nano');
INSERT INTO trades(trade,category) VALUES ('Herbs Sellers','Nano');
INSERT INTO trades(trade,category) VALUES ('Spices Sellers','Nano');
INSERT INTO trades(trade,category) VALUES ('Food Sellers','Nano');
INSERT INTO trades(trade,category) VALUES ('Patent Medicine Sellers','Nano');
INSERT INTO trades(trade,category) VALUES ('Gardeners','Nano');
INSERT INTO trades(trade,category) VALUES ('Small Holder Farmers in Poultry','Nano');
INSERT INTO trades(trade,category) VALUES ('Small Holder Farmers in Fish','Nano');
INSERT INTO trades(trade,category) VALUES ('Small Holder Farmers in Beekeeping','Nano');
INSERT INTO trades(trade,category) VALUES ('Small Holder Farmers in Snail','Nano');
INSERT INTO trades(trade,category) VALUES ('Small Holder Farmers in fruits','Nano');
INSERT INTO trades(trade,category) VALUES ('Small Holder Farmers in vegetables','Nano');
INSERT INTO trades(trade,category) VALUES ('Small Holder Farmers in Rabbit','Nano');
INSERT INTO trades(trade,category) VALUES ('Animal Husbandry and Dairy','Nano');
INSERT INTO trades(trade,category) VALUES ('Mushroom','Nano');
INSERT INTO trades(trade,category) VALUES ('Light processors','Nano');
INSERT INTO trades(trade,category) VALUES ('Baker','Nano');
INSERT INTO trades(trade,category) VALUES ('Akara Sellers','Nano');
INSERT INTO trades(trade,category) VALUES ('Street vendors and hawkers','Nano');
INSERT INTO trades(trade,category) VALUES ('Online sellers and e-commerce startups','Nano');
INSERT INTO trades(trade,category) VALUES ('Pet Handlers','Nano');
INSERT INTO trades(trade,category) VALUES ('House cleaning','Nano');
INSERT INTO trades(trade,category) VALUES ('Car washing','Nano');
INSERT INTO trades(trade,category) VALUES ('Rental businesses','Nano');
INSERT INTO trades(trade,category) VALUES ('Shoe shiners','Nano');
INSERT INTO trades(trade,category) VALUES ('Manicure/pedicure services','Nano');
INSERT INTO trades(trade,category) VALUES ('Event planning','Nano');
INSERT INTO trades(trade,category) VALUES ('Homemadejams','Nano');
INSERT INTO trades(trade,category) VALUES ('Homemade pickles','Nano');
INSERT INTO trades(trade,category) VALUES ('baked goods','Nano');
INSERT INTO trades(trade,category) VALUES ('Jewelry making','Nano');
INSERT INTO trades(trade,category) VALUES ('Private tutoring','Nano');
INSERT INTO trades(trade,category) VALUES ('Motorcycle courier services','Nano');
INSERT INTO trades(trade,category) VALUES ('Private healthcare services','Nano');
INSERT INTO trades(trade,category) VALUES ('Pharmacy stores','Micro');
INSERT INTO trades(trade,category) VALUES ('Grocery stores','Micro');
INSERT INTO trades(trade,category) VALUES ('Small restaurants','Micro');
INSERT INTO trades(trade,category) VALUES ('Food stalls','Micro');
INSERT INTO trades(trade,category) VALUES ('Beauty salons','Micro');
INSERT INTO trades(trade,category) VALUES ('Motor Mechanics','Micro');
INSERT INTO trades(trade,category) VALUES ('Electronic Repairers','Micro');
INSERT INTO trades(trade,category) VALUES ('Tailors','Micro');
INSERT INTO trades(trade,category) VALUES ('Garment Manufacturers','Micro');
INSERT INTO trades(trade,category) VALUES ('Small Holder Farmers','Micro');
INSERT INTO trades(trade,category) VALUES ('Small Scale Architects','Micro');
INSERT INTO trades(trade,category) VALUES ('Small Scale Draftsman','Micro');
INSERT INTO trades(trade,category) VALUES ('Small Scale Printers','Micro');
INSERT INTO trades(trade,category) VALUES ('Small Scale Builders','Micro');
INSERT INTO trades(trade,category) VALUES ('Building Materials','Micro');
INSERT INTO trades(trade,category) VALUES ('Restaurant & cafes with multiple locations','Micro');
INSERT INTO trades(trade,category) VALUES ('Food processing','Micro');
INSERT INTO trades(trade,category) VALUES ('Textile factories','Micro');
INSERT INTO trades(trade,category) VALUES ('Boutique','Micro');
INSERT INTO trades(trade,category) VALUES ('Bed and breakfast','Micro');
INSERT INTO trades(trade,category) VALUES ('Professional accounting firms','Micro');
INSERT INTO trades(trade,category) VALUES ('Professional law firms','Micro');
INSERT INTO trades(trade,category) VALUES ('Micro Professional consulting agencies','Micro');
INSERT INTO trades(trade,category) VALUES ('Micro-scale construction companies','Micro');
INSERT INTO trades(trade,category) VALUES ('Micro-scale contractors','Micro');
INSERT INTO trades(trade,category) VALUES ('Specialized clinics & medical practices','Micro');
INSERT INTO trades(trade,category) VALUES ('Software development firms','Micro');
INSERT INTO trades(trade,category) VALUES ('Organic farms','Micro');
INSERT INTO trades(trade,category) VALUES ('Dairy farms','Micro');
INSERT INTO trades(trade,category) VALUES ('Transportation & logistics','Micro');
INSERT INTO trades(trade,category) VALUES ('Bookstores & stationary shops','Micro');
INSERT INTO trades(trade,category) VALUES ('Family-owned and operated bakeries','Micro');
INSERT INTO trades(trade,category) VALUES ('Textile and garment manufacturing companies','Micro');
INSERT INTO trades(trade,category) VALUES ('Micro advertising agencies','Micro');
INSERT INTO trades(trade,category) VALUES ('Micro design studios','Micro');
INSERT INTO trades(trade,category) VALUES ('Constructing & Renovating residential projects','Micro');
INSERT INTO trades(trade,category) VALUES ('Eco-friendly and sustainable product companies','Micro');
INSERT INTO trades(trade,category) VALUES ('Solar panel installation companies','Micro');
INSERT INTO trades(trade,category) VALUES ('Engineering firms offering specialized services','Micro');
INSERT INTO trades(trade,category) VALUES ('Fruit processing','Micro');
INSERT INTO trades(trade,category) VALUES ('Dairy product manufacturing','Micro');
INSERT INTO trades(trade,category) VALUES ('Wholesale distribution (niche products)','Micro');
INSERT INTO trades(trade,category) VALUES ('Independent retail stores clothing boutiques','Small');
INSERT INTO trades(trade,category) VALUES ('Independent retail stores Specialty shops','Small');
INSERT INTO trades(trade,category) VALUES ('Family-owned restaurants with multiple locations','Small');
INSERT INTO trades(trade,category) VALUES ('Family-owned cafes with multiple locations','Small');
INSERT INTO trades(trade,category) VALUES ('Small-scale manufacturing companies','Small');
INSERT INTO trades(trade,category) VALUES ('small-scale food Processing plants','Small');
INSERT INTO trades(trade,category) VALUES ('Small-scale textile factories','Small');
INSERT INTO trades(trade,category) VALUES ('hotels and bed-and- breakfast establishments','Small');
INSERT INTO trades(trade,category) VALUES ('Professional services (accounting firms)','Small');
INSERT INTO trades(trade,category) VALUES ('Professional services (Law firms)','Small');
INSERT INTO trades(trade,category) VALUES ('Professional services (consulting agencies)','Small');
INSERT INTO trades(trade,category) VALUES ('Small-scale Construction companies','Small');
INSERT INTO trades(trade,category) VALUES ('Small-scale contractors','Small');
INSERT INTO trades(trade,category) VALUES ('Specialized Clinics & Medical Practices','Small');
INSERT INTO trades(trade,category) VALUES ('Small-scale Software Development firms','Small');
INSERT INTO trades(trade,category) VALUES ('Small-scale agribusiness organic farms','Small');
INSERT INTO trades(trade,category) VALUES ('Small-scale agribusiness dairy farms','Small');
INSERT INTO trades(trade,category) VALUES ('Transportation & logistics companies','Small');
INSERT INTO trades(trade,category) VALUES ('Bookstores and stationary shops','Small');
INSERT INTO trades(trade,category) VALUES ('Family-owned Bakeries with Multiple outlets','Small');
INSERT INTO trades(trade,category) VALUES ('Small-scale Garment Manufacturing companies','Small');
INSERT INTO trades(trade,category) VALUES ('Small-scale Boutique','Small');
INSERT INTO trades(trade,category) VALUES ('Creative agencies (Advertising agencies)','Small');
INSERT INTO trades(trade,category) VALUES ('Creative agencies (Design studios)','Small');
INSERT INTO trades(trade,category) VALUES ('Constructing and renovating Residential projects','Small');
INSERT INTO trades(trade,category) VALUES ('Eco-friendly and sustainable Product companies','Small');
INSERT INTO trades(trade,category) VALUES ('Renewable Energy (solar panel installation)','Small');
INSERT INTO trades(trade,category) VALUES ('Engineering firms offering Specialized services','Small');
INSERT INTO trades(trade,category) VALUES ('Agro-Processing fruit','Small');
INSERT INTO trades(trade,category) VALUES ('Agro-Processing dairy products','Small');
INSERT INTO trades(trade,category) VALUES ('Wholesale Distribution (niche products)','Small');
INSERT INTO trades(trade,category) VALUES ('Regional retail food processing plants','Medium');
INSERT INTO trades(trade,category) VALUES ('Regional retail consumer goods factories','Medium');
INSERT INTO trades(trade,category) VALUES ('Hospitality establishments (Hotels)','Medium');
INSERT INTO trades(trade,category) VALUES ('Hospitality  establishments  (Resorts)','Medium');
INSERT INTO trades(trade,category) VALUES ('Hospitality  establishments  (restaurants)','Medium');
INSERT INTO trades(trade,category) VALUES ('Construction & engineering with larger projects','Medium');
INSERT INTO trades(trade,category) VALUES ('Healthcare facilities (Specialty clinics)','Medium');
INSERT INTO trades(trade,category) VALUES ('Healthcare facilities (Diagnostic centers)','Medium');
INSERT INTO trades(trade,category) VALUES ('IT and software development companies','Medium');
INSERT INTO trades(trade,category) VALUES ('Agribusiness ventures with extensive operations','Medium');
INSERT INTO trades(trade,category) VALUES ('Logistics and transportation companies','Medium');
INSERT INTO trades(trade,category) VALUES ('Wholesale & distribution (diverse products)','Medium');
INSERT INTO trades(trade,category) VALUES ('Retail chains with regional department stores','Medium');
INSERT INTO trades(trade,category) VALUES ('Retail chains with regional specialty stores','Medium');
INSERT INTO trades(trade,category) VALUES ('Manufacturing for national distribution','Medium');
INSERT INTO trades(trade,category) VALUES ('Hospitality chains with multiple properties','Medium');
INSERT INTO trades(trade,category) VALUES ('Professional  services (legal services)','Medium');
INSERT INTO trades(trade,category) VALUES ('Professional services (Accounting services)','Medium');
INSERT INTO trades(trade,category) VALUES ('Professional services (Consulting services)','Medium');
INSERT INTO trades(trade,category) VALUES ('Construction for moderate scale/complexity','Medium');
INSERT INTO trades(trade,category) VALUES ('Professional services firms','Medium');
INSERT INTO trades(trade,category) VALUES ('Healthcare institutions (Hospitals)','Medium');
INSERT INTO trades(trade,category) VALUES ('Healthcare institutions (Medical centers)','Medium');
INSERT INTO trades(trade,category) VALUES ('Healthcare institutions (Clinics)','Medium');
INSERT INTO trades(trade,category) VALUES ('IT consulting and software development','Medium');
INSERT INTO trades(trade,category) VALUES ('Agricultural enterprises (crop farms)','Medium');
INSERT INTO trades(trade,category) VALUES ('Agricultural enterprises (livestock farms)','Medium');
INSERT INTO trades(trade,category) VALUES ('Transportation and logistics across regions','Medium');
INSERT INTO trades(trade,category) VALUES ('wholesale and distribution','Medium');
INSERT INTO trades(trade,category) VALUES ('Financial services firms (Regional banks)','Medium');
INSERT INTO trades(trade,category) VALUES ('Financial services firms (credit unions)','Medium');
INSERT INTO trades(trade,category) VALUES ('Financial services  (Insurance companies)','Medium');
INSERT INTO trades(trade,category) VALUES ('Real estate  with projects in many locations','Medium');
INSERT INTO trades(trade,category) VALUES ('Educational institutions  (schools)','Medium');
INSERT INTO trades(trade,category) VALUES ('Educational institutions (colleges)','Medium');
INSERT INTO trades(trade,category) VALUES ('Educational institutions training centers','Medium');
INSERT INTO trades(trade,category) VALUES ('Marketing and advertising agencies','Medium');
INSERT INTO trades(trade,category) VALUES ('Renewable energy companies','Medium');
INSERT INTO trades(trade,category) VALUES ('Telecom  services in multiple regions','Medium');
INSERT INTO trades(trade,category) VALUES ('Manufacturing  for national distribution','Medium');
INSERT INTO trades(trade,category) VALUES ('Environmental consulting firms','Medium');
INSERT INTO trades(trade,category) VALUES ('Non-profit organizations','Medium');
INSERT INTO trades(trade,category) VALUES ('Technology startups with regional  markets','Medium');
INSERT INTO trades(trade,category) VALUES ('Manufacturing companies (specialised products)','Medium');